all: global

global:
	git config --global user.name "Carlo Lobrano"
	git config --global user.email c.lobrano@gmail.com
	touch ~/.gitignore_global
	git config --global core.excludefiles ~/.gitignore_global
