#!/usr/bin/env bash
MAIN_INDEX=~/Dropbox/Wiki/index.md
WORK_INDEX=~/Dropbox/Work/Telit/TelitWiki/index.md
TODO_REM=~/Dropbox/Wiki/Todo.rem
TODO_TXT=~/Dropbox/Wiki/todo.txt
REMINDERS=~/Dropbox/Wiki/Reminder.md

# Create Remind file
find_duties.py -c personal -f $MAIN_INDEX --format remind > $TODO_REM
find_duties.py -c work -f $WORK_INDEX --format remind >> $TODO_REM

# Create Todo.txt file
find_duties.py -c personal -f $MAIN_INDEX --format todo > $TODO_TXT
find_duties.py -c work -f $WORK_INDEX --format todo >> $TODO_TXT

echo "===== Next ====="
remind $REMINDERS 2>/dev/null | raffaello -r "\+\w+=>green_bold @\w+=>cyan_bold @personal=>yellow_bold \(A\)=>red_bold \(B\)=>yellow_bold today=>red in\s\d+.*=>cyan tomorrow=>yellow"

echo

count=$(remind -n $REMINDERS 2>/dev/null | wc -l)
echo "===== All ($count) ====="
remind -n $REMINDERS 2>/dev/null | sort | raffaello -r "\+\w+=>green_bold @\w+=>cyan_bold @personal=>yellow_bold \(A\)=>red_bold \(B\)=>yellow_bold today=>red in\s\d+.*=>cyan tomorrow=>yellow"
