#!/usr/bin/env bash
MAIN_INDEX=~/Dropbox/Wiki/index.md
WORK_INDEX=~/Dropbox/Work/Telit/TelitWiki/index.md
TODO=~/Dropbox/Work/Telit/TelitWiki/Todo.rem
REMINDERS=~/Dropbox/Work/Telit/TelitWiki/Reminders.md

find_duties.py personal $MAIN_INDEX > $TODO
find_duties.py work $WORK_INDEX >> $TODO

echo "===== Next ====="
remind $REMINDERS 2>/dev/null | sort | raffaello -r "\+\w+=>green_bold @\w+=>cyan_bold @personal=>yellow_bold \(A\)=>red_bold \(B\)=>yellow_bold today=>red in\s\d+.*=>cyan tomorrow=>yellow"

echo

count=$(remind -n $REMINDERS 2>/dev/null | wc -l)
echo "===== All ($count) ====="
remind -n $REMINDERS 2>/dev/null | sort | raffaello -r "\+\w+=>green_bold @\w+=>cyan_bold @personal=>yellow_bold \(A\)=>red_bold \(B\)=>yellow_bold today=>red in\s\d+.*=>cyan tomorrow=>yellow"
